# Generated by Django 5.0.7 on 2024-08-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, choices=[('adjacent_highway', 'Adjacent to a highway used by vehicular traffic'), ('public_footpath', 'Public footpath or bridleway')], max_length=255, null=True)),
                ('height', models.CharField(blank=True, choices=[('below_1m', 'Below 1 meter'), ('1m_to_2m', '1 meter to 2 meters')], max_length=255, null=True)),
                ('constraint', models.CharField(blank=True, choices=[('listed_building', 'Listed building'), ('conservation_area', 'Conservation area')], max_length=255, null=True)),
                ('other', models.CharField(blank=True, choices=[('not_applicable', 'Not applicable')], max_length=255, null=True)),
                ('permission_status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
