# Generated by Django 5.0.7 on 2024-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enclosures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enclosuremodel',
            name='constraint',
            field=models.CharField(blank=True, choices=[('listed_building', 'Listed building'), ('article_2_3', 'Article 2(3) Land removing permitted development rights for the project'), ('article_2_4', 'Article 2(4) Land'), ('article_4', 'Article 4 Directive removing the PD rights for the project'), ('AONB', 'AONB'), ('works_affecting_TPO', 'Works affecting TPO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enclosuremodel',
            name='height',
            field=models.CharField(blank=True, choices=[('up_to_1m', 'Up to 1 meter'), ('above_1m', 'Above 1 meter'), ('up_to_2m', 'Up to 2 meters'), ('above_2m', 'Above 2 meters')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enclosuremodel',
            name='location',
            field=models.CharField(blank=True, choices=[('adjacent_vehicular_highway', 'Adjacent to a highway used by vehicular traffic'), ('facing_listed_building', 'Gate, fence, wall or other means of enclosure face onto a property with a listed building')], max_length=255, null=True),
        ),
    ]
